version: '3.8'
services:
  postgres:
    image: postgres:15.3
    hostname: postgres
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - local
    volumes:
      - mydata:/var/lib/postgresql/data

  app:
    container_name: action-test-app
    build: .
    ports:
      - 3000:3000
    env_file: .env
    tty: true
    depends_on:
      - postgres
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mydata:
