name: Nodes

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Run Nodes
        run: |
          docker compose -f docker-compose-nodes.yml up
